# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTPS=true
    volumes:
      - node-modules:/usr/src/app/node_modules
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/backend.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  node-modules: