# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass

volumes:
  node-modules: